// ============================================================
//  REFERANSLAR
//  /referanslar sayfasını besler.
//  Yeni firma eklemek için diziye bir satır ekleyin.
// ============================================================

// Üstteki kayan şeritte gösterilen logolar.
// Not: Görseller şu an vinc.net üzerinden çekiliyor.
// Daha hızlı ve güvenli olması için bu dosyaları
// /public/gorseller/referanslar/ klasörüne kopyalayıp
// src değerlerini "/gorseller/referanslar/1.jpg" biçimine
// çevirmeniz önerilir.
export const referenceLogos = [
  { src: "https://vinc.net/wp-content/uploads/2025/12/24_1.jpg", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/25_1.png", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/20_1.gif", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/21_1.jpg", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/26_1.png", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/23_1.jpg", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/27_1.png", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/22_1.jpg", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/29_1.jpg", alt: "Referans firma logosu" },
  { src: "https://vinc.net/wp-content/uploads/2025/12/28_1.jpg", alt: "Referans firma logosu" },
];

export const references = [
  "OYTAŞ YILDIZ ULUSLARARASI İNŞ. LTD. ŞTİ.",
  "ÖZKÖK YAPI TURZ. SAN. TİC. LTD. ŞTİ.",
  "KÖSEDAĞ İNŞ. ve TİC. LTD. ŞTİ.",
  "NAC GRUP DİJİTAL BİLG. SAN. TİC. LTD. ŞTİ.",
  "ARASCAN İNŞ. TAH. ELEKT. SAN. TİC. LTD.",
  "GÜL KELEŞOĞLU İNŞAAT SAN. ve DIŞ TİC. A.Ş.",
  "FANTOM PRODÜKSİYON",
  "TEKSER KLİMA SİSTEMLERİ",
  "MEGA TEKNİK YAY SAN. LTD. ŞTİ.",
  "MEGA MAKİNA SAN.",
  "REMA İNŞ. SAN. TİC. LTD.",
  "BSM ALÜ. İNŞ. SAN. TİC. LTD.",
  "PAYSA PREFABRİK İNŞ. SAN. TİC. LTD.",
  "DİYMAR İNŞ. SAN. TİC. LTD.",
  "PROMEK MÜH. ISIT. SAN.",
  "QUINN EMLAK YATIRIM İNŞ. VE TİC. A.Ş.",
  "DELTA DEK. İNŞ. MİM.",
  "PHERMA VİSİON A.Ş.",
  "MONO MİM. TAAH. DEK. SAN. TİC. ŞTİ.",
  "REAL HİPERMARKETLER ZİNCİRİ A.Ş.",
  "TEMPO AKS SAN. TİC. LTD. ŞTİ.",
  "NASAKOMA İNŞ. SAN. TİC. A.Ş.",
  "GÜNEY DİŞ DEPOSU TİC. SAN. A.Ş.",
  "ÜLKER GIDA SAN. TİC. A.Ş.",
  "SKY TEKS. SAĞLIK VE MATBAA",
  "MURAT MAK SAN. TİC. A.Ş.",
  "ÇEKMECE NÜKLEER ARAŞTIRMA ve EĞİTİM MERKEZİ",
  "NİLFER DEMİR ÇELİK SAN. TİC. LTD. ŞTİ.",
  "MÜSTAKİLLER İNŞAAT SAN. TİC. A.Ş.",
  "HOROZ LOJİSTİK KARGO A.Ş.",
  "THY A.Ş.",
  "ÖZYURTLAR İNŞ. ve YAPI SAN. TİC. LTD. ŞTİ.",
  "YAPI ÇÖZÜMLERİ İNŞ. SAN. TİC. LTD.",
  "ÇALIK HOLDİNG A.Ş.",
  "GÜL YAPI İNŞ. SAN. TİC. LTD.",
  "ICS İÇ VE DIŞ TİC. MÜH. İNŞ. TAAH.",
  "GÜLLÜOĞLU GIDA SAN. A.Ş.",
  "BOĞAZİÇİ ELEKTRİK DAĞITIM A.Ş.",
  "DEMİRER KAB. TES. SAN. VE TİC. A.Ş.",
  "ARK YAPI A.Ş. / MİLPA TİC. VE SAN. PAZ. A.Ş.",
  "AĞAÇKAKAN İNŞ. SAN. TİC. LTD.",
  "NESİL İNŞ. H. PROJ. SAN. TİC. LTD.",
  "MANYET MAN. TUT. TİC. SAN. LTD.",
  "ÇELİK ÇELİK YAPI ÇELİK END.",
  "PAKSU İNŞ. TUR. M. SU GETİRME SAN.",
  "ELOLOJİK ENERJİ LTD. ŞTİ.",
  "SEÇ İNŞ. SAN. TİC. LTD.",
  "DEKART İNŞ. SAN. TİC. LTD.",
  "SEZGİN ÖRME TRZM. SAN. LTD. ŞTİ.",
  "YAY TEK. VE REK. TİC. SAN. A.Ş.",
  "FUJITSU TECHNOLOGY SOLUTIONS LTD. ŞTİ.",
  "METRO GRUP A.Ş. MANAGEMENT EMLAK",
  "SKALA İNŞ. MÜH. MÜŞ.",
  "ONOK ÇELİK YAPI",
  "DELTA PROJE İNŞ. SAN. TİC. LTD.",
  "FABRİCART MEMBRAN VE METAL İNŞ. SAN. TİC. LTD.",
  "ÇETİN KAYALAR TEKSTİL İNŞ. SAN. TİC. LTD.",
  "ÖNDER İNŞ. SAN. TİC. LTD.",
  "ÇEKON İNŞ. SAN. TİC. LTD.",
  "KAYZEN YAPI ÜR. VE SİST. İNŞ. SAN. TİC. LTD.",
  "KEBAN MÜH. MİM. İNŞ. SAN. TİC. LTD.",
  "ORAY MEKANİK İNŞ. TES. LTD. ŞTİ.",
  "FENSA ÇELİK YAPI İNŞ. MAK. SAN.",
  "TERKMO SOĞUTMA SAN. A.Ş.",
  "TEMA ALÜMİNYUM SAN. A.Ş.",
  "SİNPAŞ YATIRIM VE İŞL. TİC. A.Ş.",
  "BEYAZ İNŞ. SAN. TİC. LTD.",
  "ALARKO CARRIER SAN. VE TİC. A.Ş.",
  "YEŞİL İNŞ. GAYRİMENKUL YATIRIM",
  "AYCAN DENİZCİLİK",
  "SERVET GAYRİMENKUL YATIRIM ORT.",
  "LULSOY ELEKT. İNŞ. TAAH. TİC. A.Ş.",
  "ASM İNŞ. SAN. TİC. LTD.",
  "ÇELİKÖRS İNŞ. SAN. TİC. LTD.",
  "İMOT İNŞ. MAK. SAN.",
  "AMAÇ ELEKTRİK TAAH.",
  "DÜZEY TIBBİ LTD. ŞTİ.",
  "TANRIVERDİ MEN. A.Ş.",
  "BAŞAK İNŞ. SAN. TİC. LTD.",
  "EFOR İNŞ. SAN. TİC. LTD.",
];
